BOLLINGER_PERIOD = 7
MOVING_AVERAGE_PERIOD = 7
BOLLINGER_COLUMN = 'Close'
MOVING_AVERAGE_COLUMN = 'Close'
BOLIINGER_SD = 2
PROPHET_COLUMN = 'Close'
PROPHET_PERIOD = 7
MODEL_TYPE = 'prophet'
<<<<<<< HEAD
TICKERS = ['AAPL', 'TSLA', 'BAC', 'BTC-USD', 'SPY','RIOT']
=======
TICKERS = ['AAPL', 'TSLA', 'AMZN', 'BTC-USD', 'SPY','RIOT']
BUCKET_NAME = 'wagon-data-716-el-merbouh'
TRAINING_DIRECTORY = 'trainings'
>>>>>>> master
